# -*- coding: utf-8 -*-
"""Inleiding

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TVSOjHS7mdyrTd2NFzp8hrJ-SKwIyFzj
"""

import pandas as pd
import plotly.express as px
import streamlit as st
import plotly.graph_objects as go
from menu import menu
menu()

#pip install streamlit

st.title("Inleiding tool")
st.subheader("**Doelfuncties**")
st.markdown("**Variabelen**")
st.latex(r'''
x_n = Het aandeel van productgroep n binnen het bouwproject
''')
st.latex(r'''
x_1 = Het aandeel van de productgroep buitenkozijnen, -ramen, -deuren en -puien
''')
st.latex(r'''
x_2 = Het aandeel van de productgroep lift
''')
st.latex(r'''
x_3 = Het aandeel van de productgroep binnenkozijnen en deuren
''')
st.latex(r'''
x_4 = Het aandeel van de productgroep binnenwandafwerkingen
''')
st.latex(r'''
x_5 = Het aandeel van de productgroep vloerafwerkingen
''')
st.latex(r'''
x_6 = Het aandeel van de productgroep plafonds
''')
st.latex(r'''
x_7 = Het aandeel van de productgroep sanitair
''')
st.latex(r'''
x_8 = Het aandeel van de productgroep keuken
''')
st.latex(r'''
x_9 = Het aandeel van de productgroep buitenwanden
''')
st.latex(r'''
x_10 = Het aandeel van de productgroep vloeren
''')
st.latex(r'''
x_11 = Het aandeel van de productgroep daken
''')
st.latex(r'''
x_12 = Het aandeel van de productgroep hoofddraagconstructie
''')
st.latex(r'''
x_13 = Het aandeel van de productgroep na-isolatie binnen
''')
st.latex(r'''
x_14 = Het aandeel van de productgroep riolering en HWA
''')
st.latex(r'''
x_15 = Het aandeel van de productgroep terreininrichting
''')
st.latex(r'''
x_16 = Het aandeel van de productgroep verwarming en koeling
''')
st.latex(r'''
x_17 = Het aandeel van de productgroep luchtbehandeling
''')
st.latex(r'''
x_18 = Het aandeel van de productgroep vaste gebouwvoorzieningen
''')
st.latex(r'''
x_19 = Het aandeel van de productgroep binnenwanden
''')
st.latex(r'''
x_20 = Het aandeel van de productgroep trappen en hellingen
''')
st.latex(r'''
x_21 = Het aandeel van de productgroep luiken en vensters
''')
st.latex(r'''
x_22 = Het aandeel van de productgroep balustrades en leuningen
''')
st.latex(r'''
x_23 = Het aandeel van de productgroep warm- en koud water installaties
''')
st.latex(r'''
x_24 = Het aandeel van de productgroep elektrische installaties
''')
st.latex(r'''
x_25 = Het aandeel van de productgroep beveiliging
''')

st.markdown("**Aanschafprijs**")
st.latex(r'''
f_1 = x_1 + x_2 + x_3 + x_4 + x_5 + x_6 + x_7 + x_8 + x_9 + x_10 + x_11 + x_12 + x_13 + x_14 + x_15 + x_16 + x_17 + x_18 + x_19 +
x_20 + x_21 + x_22 + x_23 + x_24 + x_25
''')

st.markdown("**Onderhoudsprijs**")
st.latex(r'''
f_2 = x_1 + x_2 + x_3 + x_4 + x_5 + x_6 + x_7 + x_8 + x_9 + x_10 + x_11 + x_12 + x_13 + x_14 + x_15 + x_16 + x_17 + x_18 + x_19 +
x_20 + x_21 + x_22 + x_23 + x_24 + x_25
''')

st.markdown("**Mate van losmaakbaarheid**")
st.latex(r'''
f_3 = x_1 + x_2 + x_3 + x_4 + x_5 + x_6 + x_7 + x_8 + x_9 + x_10 + x_11 + x_12 + x_13 + x_14 + x_15 + x_16 + x_17 + x_18 + x_19 +
x_20 + x_21 + x_22 + x_23 + x_24 + x_25
''')

st.markdown("**Toepassingsmogelijkheden**")
st.latex(r'''
f_4 = x_1 + x_2 + x_3 + x_4 + x_5 + x_6 + x_7 + x_8 + x_9 + x_10 + x_11 + x_12 + x_13 + x_14 + x_15 + x_16 + x_17 + x_18 + x_19 +
x_20 + x_21 + x_22 + x_23 + x_24 + x_25
''')

st.markdown("**Woonbeleving**")
st.latex(r'''
f_5 = x_1 + x_2 + x_3 + x_4 + x_5 + x_6 + x_7 + x_8 + x_9 + x_10 + x_11 + x_12 + x_13 + x_14 + x_15 + x_16 + x_17 + x_18 + x_19 +
x_20 + x_21 + x_22 + x_23 + x_24 + x_25
''')

st.markdown("**Milieubelasting**")
st.latex(r'''
f_6 = x_1 + x_2 + x_3 + x_4 + x_5 + x_6 + x_7 + x_8 + x_9 + x_10 + x_11 + x_12 + x_13 + x_14 + x_15 + x_16 + x_17 + x_18 + x_19 +
x_20 + x_21 + x_22 + x_23 + x_24 + x_25
''')

st.markdown("**Flexibiliteit tbv toekomstbestendigheid en innovatie**")
st.latex(r'''
f_7 = x_1 + x_2 + x_3 + x_4 + x_5 + x_6 + x_7 + x_8 + x_9 + x_10 + x_11 + x_12 + x_13 + x_14 + x_15 + x_16 + x_17 + x_18 + x_19 +
x_20 + x_21 + x_22 + x_23 + x_24 + x_25
''')

st.markdown("**Mate van standaardisering**")
st.latex(r'''
f_8 = x_1 + x_2 + x_3 + x_4 + x_5 + x_6 + x_7 + x_8 + x_9 + x_10 + x_11 + x_12 + x_13 + x_14 + x_15 + x_16 + x_17 + x_18 + x_19 +
x_20 + x_21 + x_22 + x_23 + x_24 + x_25
''')

labels = ["Buitenkozijnen, -ramen, -deuren en -puien", "Lift", "Binnenkozijnen en deuren",
                  "Binnenwandafwerkingen", "Vloerafwerkingen", "Plafonds", "Sanitair", "Keuken", "Buitenwanden",
                 "Vloeren", "Daken", "Hoofddraagconstructie", "Na-isolatie binnen", "Riolering en HWA", "Terreininrichting",
                 "Verwarming en koeling", "Luchtbehandeling", "Vaste gebouwvoorzieningen", "Binnenwanden",
                 "Trappen en hellingen", "Luiken en vensters", "Balustrades en leuningen", "Warm- en koud water installaties",
                 "Elektrische installaties", "Beveiliging"]
values = [10, 10, 8, 9, 4, 7, 6, 2, 4, 3, 2, 1, 2, 3, 4, 5, 3, 7, 3, 2, 1, 1, 1, 1, 1]
print(sum(values))

fig = px.pie(values=values, names=labels)
st.plotly_chart(fig)

