# -*- coding: utf-8 -*-
"""Opbouw.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WlvpuyevshddWkngPkbqDbm9rAZwQlBh
"""

import streamlit as st
import pandas as pd
import plotly.express as px

import streamlit as st
st.title("Eigen Haard")
tab1, tab2, tab3 = st.tabs(["Input", "Optimalisatie", "Aanpassingen"])

import streamlit as st

with tab1:
  st.markdown("**Soort project**")
  st.selectbox(
    'Om wat voor soort project gaat het?',
    ['Nieuwbouw woningen', 'Renovatie'],
    index=None,
    placeholder="Selecteer een soort project"
  )

  st.markdown("**Projectfase**")
  st.selectbox(
    "Wat is de fase van het project?",
    ["Initiële fase", "Ontwerp fase"],
    index = None,
    placeholder = "Selecteer de fase van het project"
    )

  st.markdown("**Budget**")
  st.number_input("Vul het budget in voor het huidige project", value=None, placeholder="Typ een bedrag")

  st.markdown("**Wegingen**")
  st.markdown("Hieronder kan er per thema aangegeven worden of deze zwaarder of minder zwaar meeweegt tijdens dit project. "
   "Als een thema neutraal is kan deze op '0' blijven staan. Als een thema zwaader meeweegt kan deze op +1 of +2 staan, "
   "als een thema minder zwaar meeweegt kan deze op -1 of -2 gezet worden. ")
  st.number_input("Vul de weging in voor het thema 'Woonbeleving' in dit project", value=0, min_value = -2, max_value = 2)
  st.number_input("Vul de weging in voor het thema 'Duurzaam' in dit project", value=0, min_value = -2, max_value = 2)
  st.number_input("Vul de weging in voor het thema 'Prijs' in dit project", value=0, min_value = -2, max_value = 2)

with tab2:
  st.markdown("In dit project, is het optimaal om het aandeel van de productgroepen als volgt in te delen:")
  st.markdown('''- De productgroep Keukens 20% van het totale project

  - De productgroep Sanitair 15% van het totale project

  - De productgroep Na-isolatie 7% van het totale project

  - De productgroep Trappen 15% van het totale project

  - De productgroep Vloeren 8% van het totale project

  - De productgroep Buitenwanden 15% van het totale project

  - De productgroep Vloerafwerking 20% van het totale project''')

  fig1 = px.pie(values=[20, 15, 7, 15, 8, 15, 20], names=['Keuken', 'Sanitair', 'Na-isolatie', 'Trappen', 'Vloeren', 'Buitenwanden', 'Vloerafwerking'], color_discrete_sequence=px.colors.sequential.RdBu)

  st.plotly_chart(fig1)

  st.markdown("Hierbij wordt rekening gehouden met de volgende wegingen van de thema's")


# Maak een lijnplot met Plotly Express
  fig = px.bar(x=['Prijs', 'Woonbeleving', 'Duurzaamheid'], y=[1, 2, -2], color=[1, 2, 0], color_continuous_scale='blues', range_color=(-2, 2))
  fig.update_yaxes(range=[-2, 2], tickvals=[-2, -1, 0, 1, 2], tickmode='array')
  st.plotly_chart(fig)

